services:
  postgres:
    image: postgres:15-alpine
    container_name: anxiety_bot_postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 1s
      retries: 10
    environment:
      POSTGRES_DB: "${POSTGRES_DBNAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - bot_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: anxiety_bot_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - bot_network

  bot:
    image: alpine
    container_name: anxiety_bot
    restart: unless-stopped
    build: .
    volumes:
      - ./migrations:/db_migrations
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      POSTGRES_HOST: postgres
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DBNAME: "${POSTGRES_DBNAME}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_MIGRATIONS: "${POSTGRES_MIGRATIONS}"
      RATE_LIMIT_TIME: "${RATE_LIMIT_TIME}"
      RATE_LIMIT: "${RATE_LIMIT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
