services:
  redis:
    image: redis:7-alpine
    container_name: anxiety_bot_redis
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6445:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 5
    networks:
      - bot_network

  bot:
    container_name: anxiety_bot
    restart: unless-stopped
    build: .
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
